import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { Roboto } from "next/font/google";
import styles from "@/styles/Home.module.css";
import FilmReel from "@/components/FilmReel";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const images = [
    "https://images.pexels.com/photos/10297667/pexels-photo-10297667.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    "https://images.pexels.com/photos/7541692/pexels-photo-7541692.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    "https://images.pexels.com/photos/14080409/pexels-photo-14080409.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  ];

  const handleLogin = () => {
    window.location.assign("/feed");
  };

  return (
    <>
      <Head>
        <title>SocialWave</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main id="hero-screen">
      <Image src={"/images/700821.png"} alt="background img" fill={true} className={"absolute -z-10"} />
        <div className="min-h-screen flex items-center justify-center object-center z-50">
          <div className="text-center w-full sm:w-3/4 md:w-1/3 rounded-xl bg-white py-10 shadow-lg">
            <div id="login-box-header" className=" my-5">
              <h1 className="text-blue-400 text-6xl font-bold">SocialWave</h1>
              <p className="text-gray-500 text-lg">
                Ride the wave of connection
              </p>
            </div>
            <div id="login-box-body" className="text-left p-5">
              <form className="space-y-2 md:space-y-2" action="#">
                <div>
                  <label className="block mb-2 text-sm font-medium text-gray-500 ">
                    Your email
                  </label>
                  <input
                    type="email"
                    name="email"
                    id="email"
                    className="bg-gray-50 border border-gray-300 text-gray-500 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 "
                    placeholder="name@example.com"
                    required={true}
                  />
                </div>
                <div>
                  <label className="block mb-2 text-sm font-medium text-gray-500">
                    Password
                  </label>
                  <input
                    type="password"
                    name="password"
                    id="password"
                    placeholder="••••••••"
                    className="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 "
                    required={true}
                  />
                </div>
                <div className="flex items-center justify-between">
                  <div className="flex items-start">
                    <div className="flex items-center h-5">
                      <input
                        id="remember"
                        aria-describedby="remember"
                        type="checkbox"
                        className="w-4 h-4 border border-gray-300 rounded bg-gray-50 focus:ring-3 focus:ring-primary-300 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-primary-600 dark:ring-offset-gray-800"
                        required={true}
                      />
                    </div>
                    <div className="ml-3 text-sm">
                      <label className="text-gray-500">Remember me</label>
                    </div>
                  </div>
                  <Link
                    href="/recover"
                    className="text-sm font-medium text-primary-600 hover:underline dark:text-primary-500"
                  >
                    Forgot password?
                  </Link>
                </div>
                <button
                  type="submit"
                  className="w-1/4 text-white bg-blue-400 hover:bg-blue-500 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center"
                  onClick={handleLogin}
                >
                  Sign in
                </button>
                <p className="text-sm font-light text-gray-500">
                  Don&apos;t have an account yet?{" "}
                  <Link
                    href="/register"
                    className="font-medium text-primary-600 hover:underline dark:text-primary-500"
                  >
                    Sign up
                  </Link>
                </p>
              </form>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
